apiVersion: v1
kind: ConfigMap
metadata:
  name: manyface
data:
  manyface.yaml: |
    rest: 
      protocol: http
      host: localhost
      port: 8080
    grpc:
      protocol: http
      host: localhost
      port: 5300
    matrix:
      protocol: http
      host: localhost
      port: 8008
    db:
      file: /app/db/data.db
    log:
      file: ./server.log
