apiVersion: apps/v1
kind: Deployment
metadata:
  name: manyface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manyface
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: manyface
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - image: docker.io/olaesean/manyface:golang1.17.5
        name: manyface
        command: ["/go/bin/manyface"]
        imagePullPolicy: Always
        ports:
        - name: rest
          containerPort: 8080
        - name: grpc
          containerPort: 5300
        resources:
          requests:
            memory: 150Mi
        env:
        - name: CFG
          value: /app/configs
        volumeMounts:
        - name: configs
          mountPath: /app/configs
          readOnly: true
        - name: db
          mountPath: /app/db
      volumes:
      - name: db
        persistentVolumeClaim: 
          claimName: manyface
      - name: configs
        configMap: 
          name: manyface
