apiVersion: v1
kind: Service
metadata:
  name: manyface
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: 80
    targetPort: 8080
  - name: grpc
    port: 5300
    protocol: TCP
  selector:
    app: manyface