apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: centosadmin/utils:0.3
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: data
      mountPath: /data
    - name: configs
      mountPath: /configs
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: manyface
  - name: configs
    configMap:
      name: manyface
