rest: 
  protocol: http
  host: localhost
  port: 8080

grpc:
  protocol: http
  host: localhost
  port: 5300

matrix:
  protocol: http
  host: localhost
  port: 8009

data:
  # file: ./db/data.db
  # file: /app/db/data.db
  # file: ../../db/data.db
  db: /Users/i070933/Github/matrix/manyface/db/data.db  # TODO: remove
  blob: /Users/i070933/Github/matrix/manyface/db/blob/  # TODO: remove

log:
  file: ./server.log
